FROM node:16-alpine
WORKDIR /app
COPY frontend/package.json frontend/yarn.lock ./
RUN yarn install --frozen-lockfile
COPY frontend/ .
RUN yarn build
RUN yarn global add serve
CMD ["serve", "-s", "build", "-l", "3000"]